import { Inter,Roboto } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'
import Container from '@/components/Container'
import { ThemeProvider } from '@/context/ThemeContext'

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'blog-app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
     
        <ThemeProvider>
        <Container>
          <Navbar />
          <div className=''>
            {children}
          </div>
          
          <Footer />
          </Container>
        </ThemeProvider>
        
       
        </body>
    </html>
  )
}
